server:
  port: 9003
spring:
  application:
    name: Res-Service-ApiGateway
  cloud:
    gateway:
      routes:
        - id: res-order
          uri: lb://restaurant-order
          predicates:
            - Path=/res/v1/*
            - Method=GET,POST,PUT,DELETE
        - id: res-order-path
          uri: lb://restaurant-order
          predicates:
            - Path=/res/v1/*/*
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: order
                fallbackUri: forward:/fallback/restaurantFallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
