spring:
  cloud:
    gateway:
      routes:
        - id: res-order
          uri: lb://restaurant-order
          predicates:
            - Path=/res/v1/*
            - Method=GET,POST,PUT,DELETE
        - id: res-order-path
          uri: lb://restaurant-order
          predicates:
            - Path=/res/v1/*/*
            - Method=GET,POST,PUT,DELETE

